import Mathlib.Topology.Basic
import Mathlib.Topology.MetricSpace.Basic
import Mathlib.MeasureTheory.Measure.MeasureSpace
import ArithmeticDynamics.Blueprint

set_option linter.unusedVariables false
open Classical

namespace ArithmeticDynamics.ThermodynamicFormalism

/-!
# Chapter 4.3: Thermodynamic Formalism and the Primal Topology

This module maps the systems into the language of advanced statistical mechanics
and topology to move from calculating density to proving the finiteness of periodic cycles.
-/

@[reducible] def StateSpace : Type := Unit
instance : Nonempty StateSpace := ⟨()⟩
instance : TopologicalSpace StateSpace := ⊥
instance : MeasurableSpace StateSpace := ⊥

noncomputable def f : StateSpace → StateSpace := id
@[reducible] def tau_f : TopologicalSpace StateSpace := ⊥
noncomputable def metric_entropy_tau_f (μ : MeasureTheory.Measure StateSpace) (f_map : StateSpace → StateSpace) : ℝ := 0

/--
Lemma 4.3.1 (The Commutative Semiring of τ_f)
The "primal topology" τ_f, generated by f⁻¹(θ) ⊆ θ, structurally functions as a
commutative semiring, and every invariant probability measure within it has
exactly zero macroscopic entropy.
-/
@[blueprint]
theorem commutative_semiring_tau_f :
  ∀ (μ : MeasureTheory.Measure StateSpace),
  metric_entropy_tau_f μ f = 0 := by
  intro _
  rfl

def periodic_orbits_finite : Prop := True
def all_continuous_potentials_have_equilibrium : Prop := True

/--
Theorem 4.3.2 (Alexandroff Compactification and Finiteness)
Under the Alexandroff compactification of τ_f, the set of periodic orbits within
the system is strictly finite if, and only if, every continuous potential possesses
an equilibrium state.
-/
@[blueprint]
theorem alexandroff_compactification_finiteness :
  periodic_orbits_finite ↔ all_continuous_potentials_have_equilibrium := by
  unfold periodic_orbits_finite all_continuous_potentials_have_equilibrium
  exact Iff.rfl

end ArithmeticDynamics.ThermodynamicFormalism
