import argparse
import json
import sys
import numpy as np
import scipy.linalg as la


def parse_args():
    parser = argparse.ArgumentParser(
        description="Monte Carlo simulation of transition matrix eigenvalues."
    )
    parser.add_argument(
        "--input",
        default="data/matrix_data.json",
        help="Path to the JSON file with system parameters (default: data/matrix_data.json)",
    )
    parser.add_argument(
        "--output",
        default="results/phase1_results.txt",
        help="Path to write simulation results (default: results/phase1_results.txt)",
    )
    parser.add_argument(
        "--samples",
        type=int,
        default=100_000_000,
        help="Number of random large integer orbits to simulate (default: 100000000)",
    )
    return parser.parse_args()


def load_system(input_path):
    """Loads the formally verified parameters from the JSON generated by Lean."""
    print(f"Loading Lean 4 parameters from {input_path}...")
    try:
        with open(input_path, "r") as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"ERROR: {input_path} not found. Ensure the Lean script has exported it.")
        sys.exit(1)

    d = data["modulus"]
    a = np.array(data["a"], dtype=np.int64)
    b = np.array(data["b"], dtype=np.int64)

    print(f"Loaded System Modulus: {d}")
    print(f"Multipliers (a): {a}")
    print(f"Addends (b):     {b}")
    return d, a, b


def simulate_transitions(d, a, b, N):
    """Runs a vectorized Monte Carlo simulation to estimate the transition matrix."""
    print(f"Simulating {N} random large integer orbits...")

    # Generate N random very large integers
    # We use a large high boundary to simulate the asymptotic uniform distribution
    # np.random.randint's max bound for int64 is 2**63 - 1
    # We will just generate random int64s.
    # To ensure they are positive we use high=2**62
    x = np.random.randint(0, 2**62, size=N, dtype=np.int64)

    # Calculate starting residue class
    i_vals = (x % d).astype(np.int32)

    # Apply the corresponding map branch: f(x) = (a[i]*x + b[i]) // d
    # Since numpy arrays can be indexed by another array, we can vectorize this
    fx = (a[i_vals] * x + b[i_vals]) // d

    # Calculate destination residue class
    j_vals = (fx % d).astype(np.int32)

    # Build the transition matrix P_empirical
    # Use np.bincount for faster 2D histogram (optimized in C)
    counts = np.bincount(i_vals * d + j_vals, minlength=d * d)
    P_empirical = counts.reshape((d, d)).astype(np.float64)

    print("\nRaw Transition Counts:")
    print(P_empirical)

    # Normalize rows so they sum to 1
    row_sums = P_empirical.sum(axis=1, keepdims=True)
    # Avoid division by zero, though highly unlikely with 10^8 samples
    P_empirical = np.divide(
        P_empirical, row_sums, out=np.zeros_like(P_empirical), where=row_sums != 0
    )

    print("\nEmpirical Transition Matrix P_empirical:")
    print(np.round(P_empirical, 4))
    return P_empirical


def analyze_eigenvalues(P_empirical):
    """Calculates and sorts the eigenvalues of the transition matrix."""
    print("\nCalculating eigenvalues...")
    eigenvalues, _ = la.eig(P_empirical)

    # Sort eigenvalues by absolute value descending
    sorted_indices = np.argsort(np.abs(eigenvalues))[::-1]
    sorted_eigenvalues = eigenvalues[sorted_indices]

    print(f"Eigenvalues: {np.round(sorted_eigenvalues, 4)}")
    return sorted_eigenvalues


def report_results(sorted_eigenvalues, output_path):
    """Processes, displays, and saves the simulation results."""
    if len(sorted_eigenvalues) > 1:
        lambda_1 = sorted_eigenvalues[0]
        lambda_2 = sorted_eigenvalues[1]

        print(f"\nDominant Eigenvalue (λ_1): {np.abs(lambda_1):.6f}")
        print(f"Second Largest Eigenvalue (λ_2): {np.abs(lambda_2):.6f}")

        spectral_gap = 1.0 - np.abs(lambda_2)
        print(f"\nEstimated Empirical Spectral Gap (1 - |λ_2|): {spectral_gap:.6f}")

        if 0 < spectral_gap < 1.0:
            msg = (
                "SUCCESS: Empirically observed strict spectral gap. "
                "This Monte Carlo estimate provides evidence (not a mathematical proof) "
                "that the system may be rapidly mixing."
            )
        else:
            msg = "WARNING: No empirical spectral gap found in this estimate."
        print(msg)
        with open(output_path, "w") as out:
            out.write(f"Dominant Eigenvalue (lambda_1): {np.abs(lambda_1):.6f}\n")
            out.write(f"Second Largest Eigenvalue (lambda_2): {np.abs(lambda_2):.6f}\n")
            out.write(
                f"Estimated Empirical Spectral Gap (1 - |lambda_2|): {spectral_gap:.6f}\n"
            )
            out.write(msg + "\n")
    else:
        print("Not enough eigenvalues to calculate spectral gap.")


def main():
    args = parse_args()
    d, a, b = load_system(args.input)
    P_empirical = simulate_transitions(d, a, b, args.samples)
    sorted_eigenvalues = analyze_eigenvalues(P_empirical)
    report_results(sorted_eigenvalues, args.output)

if __name__ == "__main__":
    main()
