import argparse
import json
import sys
import numpy as np
import matplotlib.pyplot as plt


def parse_args():
    parser = argparse.ArgumentParser(
        description="Compute and plot the asymptotic density of the attracting set."
    )
    parser.add_argument(
        "--input",
        default="data/matrix_data.json",
        help="Path to the JSON file with system parameters (default: data/matrix_data.json)",
    )
    parser.add_argument(
        "--output",
        default="assets/density_bound_proof.png",
        help="Path to save the output plot (default: assets/density_bound_proof.png)",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=10_000_000,
        help="Upper integer limit N for the exhaustive orbit search (default: 10000000)",
    )
    return parser.parse_args()


def load_system(input_path):
    """Loads the formally verified parameters from the JSON generated by Lean."""
    try:
        with open(input_path, "r") as f:
            data = json.load(f)
        return data["modulus"], np.array(data["a"], dtype=np.int64), np.array(data["b"], dtype=np.int64)
    except FileNotFoundError:
        print(f"ERROR: {input_path} not found. Ensure the Lean script has exported it.")
        sys.exit(1)

def find_primary_attractor(d, a, b):
    """Dynamically discovers the primary periodic cycle (the attractor)."""
    x = 1
    seen = {}  # dict: value -> insertion index for O(1) lookup
    idx = 0
    while x not in seen:
        seen[x] = idx
        res = x % d
        x = (int(a[res]) * x + int(b[res])) // d
        idx += 1
    cycle_start = seen[x]
    seen_list = list(seen.keys())
    return tuple(seen_list[cycle_start:])

def compute_density(d, a, b, N):
    """Exhaustively computes orbits using a high-performance numpy cache."""
    attractor = find_primary_attractor(d, a, b)
    print(f"Primary Attracting Set Discovered: {attractor}")

    # Allocate a massive memory cache to prevent OOB errors during expansion
    CACHE_SIZE = int(N * 10)
    cache = np.zeros(CACHE_SIZE, dtype=np.int8)

    # Pre-seed the cache with the known attractor
    for node in attractor:
        if node < CACHE_SIZE:
            cache[node] = 1

    pi_x = np.zeros(N + 1, dtype=np.int64)
    success_count = 0

    print(f"Executing exhaustive memoized search up to {N:,}...")

    for x in range(1, N + 1):
        path = []
        current = x

        while True:
            if current < CACHE_SIZE and cache[current] != 0:
                result = cache[current]
                break

            path.append(current)
            res = current % d
            current = (int(a[res]) * current + int(b[res])) // d

            # Failsafe for integer escape
            if current >= CACHE_SIZE:
                result = -1
                break

        # Backpropagate
        for node in path:
            if node < CACHE_SIZE:
                cache[node] = result

        if result == 1:
            success_count += 1

        pi_x[x] = success_count

        if x % max(1, N // 10) == 0:
            print(f"  Processed {x:,} / {N:,} ({(x/N)*100:.0f}%)")

    return pi_x

def evaluate_and_plot(N, pi_x, output_path="assets/density_bound_proof.png"):
    """Evaluates the bound programmatically and generates the visual proof."""
    print("\nEvaluating Asymptotic Bound...")

    x_vals = np.arange(1, N + 1, dtype=np.float64)
    y_empirical = pi_x[1:]

    c = 0.5
    epsilon = 0.05
    y_target = c * np.power(x_vals, 1.0 - epsilon)

    # PROGRAMMATIC PASS/FAIL CHECK
    # We ignore the first 1,000 integers to avoid trivial small-number noise
    valid_indices = x_vals > 1000
    if np.all(y_empirical[valid_indices] >= y_target[valid_indices]):
        print(f"*** RESULT: PASS ***")
        print(f"The empirical density strictly bounds the target c*x^(1-e) for c={c}, e={epsilon}.")
    else:
        print(f"*** RESULT: FAIL ***")
        print(f"The empirical density dropped below the target bound. Consider increasing epsilon.")

    # Generate the log-log plot for the dissertation
    plt.figure(figsize=(10, 6))
    plt.plot(x_vals, x_vals, 'k--', alpha=0.3, label='Theoretical Maximum ($\pi(x) = x$)')
    plt.plot(x_vals, y_empirical, 'b-', linewidth=2, label='Empirical Convergence $\pi_{\mathcal{A}}(x)$')
    plt.plot(x_vals, y_target, 'r--', linewidth=2, label=f'Target Bound ($0.5 x^{{0.95}}$)')

    plt.xscale('log')
    plt.yscale('log')
    plt.xlabel('Integer $x$ (Log Scale)')
    plt.ylabel('Count of Convergent Orbits (Log Scale)')
    plt.title('Asymptotic Density of the $d=5$ Pilot System')
    plt.legend()
    plt.grid(True, which="both", ls="--", alpha=0.5)

    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    print(f"Visual proof saved as '{output_path}'.")

if __name__ == "__main__":
    args = parse_args()
    d, a, b = load_system(args.input)
    N = args.limit
    pi_x = compute_density(d, a, b, N)
    evaluate_and_plot(N, pi_x, args.output)
